# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-09 06:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_auto_20170409_0655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='date_of_birth',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 4, 9, 6, 56, 39, 948184)),
        ),
        migrations.AlterField(
            model_name='survey',
            name='enddate',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 9, 6, 56, 39, 937545)),
        ),
    ]
