# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-09 07:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_auto_20170409_0656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='date_of_birth',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 4, 9, 7, 4, 52, 859592)),
        ),
        migrations.AlterField(
            model_name='survey',
            name='enddate',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 9, 7, 4, 52, 848878)),
        ),
    ]
