# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-09 08:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0004_auto_20170409_0704'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mail',
            options={'verbose_name': ' Employees ', 'verbose_name_plural': ' Staff Details '},
        ),
        migrations.AlterField(
            model_name='mail',
            name='date_of_birth',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 4, 9, 8, 11, 32, 530822)),
        ),
        migrations.AlterField(
            model_name='mail',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='survey.Department'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='enddate',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 9, 8, 11, 32, 520205)),
        ),
    ]
