# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-09 09:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0005_auto_20170409_0811'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mail',
            old_name='employeeid',
            new_name='Employeeid',
        ),
        migrations.RenameField(
            model_name='mail',
            old_name='name',
            new_name='Name',
        ),
        migrations.AlterField(
            model_name='mail',
            name='date_of_birth',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 4, 9, 9, 30, 3, 795799)),
        ),
        migrations.AlterField(
            model_name='survey',
            name='enddate',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 9, 9, 30, 3, 785118)),
        ),
    ]
