# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-09 09:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0006_auto_20170409_0930'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mail',
            old_name='Employeeid',
            new_name='employeeid',
        ),
        migrations.RenameField(
            model_name='mail',
            old_name='Name',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='mail',
            name='date_of_birth',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 4, 9, 9, 31, 20, 598447)),
        ),
        migrations.AlterField(
            model_name='survey',
            name='enddate',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 9, 9, 31, 20, 587885)),
        ),
    ]
