# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-10 15:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0009_auto_20170409_0940'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail',
            name='user_uuid',
            field=models.IntegerField(default=72),
        ),
        migrations.AlterField(
            model_name='mail',
            name='date_of_birth',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 4, 10, 15, 20, 40, 183745)),
        ),
        migrations.AlterField(
            model_name='mail',
            name='end_date',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 4, 10, 15, 20, 40, 183824)),
        ),
        migrations.AlterField(
            model_name='mail',
            name='start_date',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 4, 10, 15, 20, 40, 183790)),
        ),
        migrations.AlterField(
            model_name='survey',
            name='enddate',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 10, 15, 20, 40, 173053)),
        ),
    ]
