# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-10 15:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0010_auto_20170410_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='date_of_birth',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 4, 10, 15, 25, 32, 191920)),
        ),
        migrations.AlterField(
            model_name='mail',
            name='end_date',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 4, 10, 15, 25, 32, 191999)),
        ),
        migrations.AlterField(
            model_name='mail',
            name='start_date',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 4, 10, 15, 25, 32, 191965)),
        ),
        migrations.AlterField(
            model_name='mail',
            name='user_uuid',
            field=models.IntegerField(default=1061),
        ),
        migrations.AlterField(
            model_name='survey',
            name='enddate',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 10, 15, 25, 32, 181276)),
        ),
    ]
