# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-12 16:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0017_auto_20170410_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='date_of_birth',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 4, 12, 16, 4, 2, 465225)),
        ),
        migrations.AlterField(
            model_name='mail',
            name='end_date',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 4, 12, 16, 4, 2, 465355)),
        ),
        migrations.AlterField(
            model_name='mail',
            name='start_date',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 4, 12, 16, 4, 2, 465300)),
        ),
        migrations.AlterField(
            model_name='mail',
            name='user_uuid',
            field=models.IntegerField(default=662, editable=False),
        ),
        migrations.AlterField(
            model_name='survey',
            name='enddate',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 12, 16, 4, 2, 447461)),
        ),
    ]
