# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-12 17:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0018_auto_20170412_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='responder',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='survey.Mail'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mail',
            name='date_of_birth',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 4, 12, 17, 38, 34, 598775)),
        ),
        migrations.AlterField(
            model_name='mail',
            name='end_date',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 4, 12, 17, 38, 34, 598889)),
        ),
        migrations.AlterField(
            model_name='mail',
            name='start_date',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 4, 12, 17, 38, 34, 598839)),
        ),
        migrations.AlterField(
            model_name='mail',
            name='user_uuid',
            field=models.IntegerField(default=11, editable=False),
        ),
        migrations.AlterField(
            model_name='survey',
            name='enddate',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 12, 17, 38, 34, 590629)),
        ),
    ]
